# Generated by Django 6.0.3 on 2026-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=2000)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="media/photos/"),
                ),
            ],
        ),
    ]
