# Generated by Django 6.0.3 on 2026-04-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField()),
                ("year", models.IntegerField()),
                ("students", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=200)),
                ("supervisor", models.CharField(max_length=200)),
                (
                    "report_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("keywords", models.CharField(blank=True, max_length=500, null=True)),
                ("areas", models.CharField(blank=True, max_length=500, null=True)),
                ("image", models.CharField(blank=True, max_length=2000, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("background_color", models.CharField(default="", max_length=20)),
                ("text_color", models.CharField(default="", max_length=20)),
                ("icon", models.CharField(default="", max_length=100)),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_projects",
                        to="portfolio.course",
                    ),
                ),
            ],
        ),
    ]
